timeout_seconds: 5
apps:
  - id: app1
    name: App1
    urls:
      dev:
        east: http://127.0.0.1:9001/app1/dev/east/actuator/info
        west: N/A
      uat:
        east: http://127.0.0.1:9001/app1/uat/east/actuator/info
        west: http://127.0.0.1:9001/app1/uat/west/actuator/info
      sit:
        east: http://127.0.0.1:9001/app1/sit/east/actuator/info
        west: http://127.0.0.1:9001/app1/sit/west/actuator/info
      perf:
        east: http://127.0.0.1:9001/app1/perf/east/actuator/info
        west: http://127.0.0.1:9001/app1/perf/west/actuator/info
      prod:
        east: http://127.0.0.1:9001/app1/prod/east/actuator/info
        west: http://127.0.0.1:9001/app1/prod/west/actuator/info
  - id: app2
    name: App2
    urls:
      dev:
        east: http://127.0.0.1:9001/app2/dev/east/actuator/info
        west: N/A
      uat:
        east: http://127.0.0.1:9001/app2/uat/east/actuator/info
        west: http://127.0.0.1:9001/app2/uat/west/actuator/info
      sit:
        east: http://127.0.0.1:9001/app2/sit/east/actuator/info
        west: http://127.0.0.1:9001/app2/sit/west/actuator/info
      perf:
        east: http://127.0.0.1:9001/app2/perf/east/actuator/info
        west: http://127.0.0.1:9001/app2/perf/west/actuator/info
      prod:
        east: http://127.0.0.1:9001/app2/prod/east/actuator/info
        west: http://127.0.0.1:9001/app2/prod/west/actuator/info
  - id: app3
    name: App3
    urls:
      dev:
        east: http://127.0.0.1:9001/app3/dev/east/actuator/info
        west: N/A
      uat:
        east: http://127.0.0.1:9001/app3/uat/east/actuator/info
        west: http://127.0.0.1:9001/app3/uat/west/actuator/info
      sit:
        east: http://127.0.0.1:9001/app3/sit/east/actuator/info
        west: http://127.0.0.1:9001/app3/sit/west/actuator/info
      perf:
        east: http://127.0.0.1:9001/app3/perf/east/actuator/info
        west: http://127.0.0.1:9001/app3/perf/west/actuator/info
      prod:
        east: http://127.0.0.1:9001/app3/prod/east/actuator/info
        west: http://127.0.0.1:9001/app3/prod/west/actuator/info
